/**
 * Constants and enums for Legifrance API
 */

export enum Fond {
  JORF = 'JORF',
  CNIL = 'CNIL',
  CETAT = 'CETAT',
  JURI = 'JURI',
  JUFI = 'JUFI',
  CONSTIT = 'CONSTIT',
  KALI = 'KALI',
  CODE_DATE = 'CODE_DATE',
  CODE_ETAT = 'CODE_ETAT',
  LODA_DATE = 'LODA_DATE',
  LODA_ETAT = 'LODA_ETAT',
  ALL = 'ALL',
  CIRC = 'CIRC',
  ACCO = 'ACCO',
}

export enum Nature {
  LOI = 'LOI',
  ORDONNANCE = 'ORDONNANCE',
  DECRET = 'DECRET',
  ARRETE = 'ARRETE',
  DECRET_LOI = 'DECRET_LOI',
  CONSTITUTION = 'CONSTITUTION',
  DECISION = 'DECISION',
  CONVENTION = 'CONVENTION',
  DECLARATION = 'DECLARATION',
  ACCORD_FONCTION_PUBLIQUE = 'ACCORD_FONCTION_PUBLIQUE',
}

export enum TypeChamp {
  ALL = 'ALL',
  TITLE = 'TITLE',
  TABLE = 'TABLE',
  NOR = 'NOR',
  NUM = 'NUM',
  ADVANCED_TEXTE_ID = 'ADVANCED_TEXTE_ID',
  NUM_DELIB = 'NUM_DELIB',
  NUM_DEC = 'NUM_DEC',
  NUM_ARTICLE = 'NUM_ARTICLE',
  ARTICLE = 'ARTICLE',
  MINISTERE = 'MINISTERE',
  VISA = 'VISA',
  NOTICE = 'NOTICE',
  VISA_NOTICE = 'VISA_NOTICE',
  TRAVAUX_PREP = 'TRAVAUX_PREP',
  SIGNATURE = 'SIGNATURE',
  NOTA = 'NOTA',
  NUM_AFFAIRE = 'NUM_AFFAIRE',
  ABSTRATS = 'ABSTRATS',
  RESUMES = 'RESUMES',
  TEXTE = 'TEXTE',
  ECLI = 'ECLI',
  NUM_LOI_DEF = 'NUM_LOI_DEF',
  TYPE_DECISION = 'TYPE_DECISION',
  NUMERO_INTERNE = 'NUMERO_INTERNE',
  REF_PUBLI = 'REF_PUBLI',
  RESUME_CIRC = 'RESUME_CIRC',
  TEXTE_REF = 'TEXTE_REF',
  TITRE_LOI_DEF = 'TITRE_LOI_DEF',
  RAISON_SOCIALE = 'RAISON_SOCIALE',
  MOTS_CLES = 'MOTS_CLES',
  IDCC = 'IDCC',
}

export enum Operateur {
  ET = 'ET',
  OU = 'OU',
  SAUF = 'SAUF',
  PROX = 'PROX',
}

export enum TypeRecherche {
  UN_DES_MOTS = 'UN_DES_MOTS',
  EXACTE = 'EXACTE',
  TOUS_LES_MOTS_DANS_UN_CHAMP = 'TOUS_LES_MOTS_DANS_UN_CHAMP',
  AUCUN_DES_MOTS = 'AUCUN_DES_MOTS',
  AUCUNE_CORRESPONDANCE_A_CETTE_EXPRESSION = 'AUCUNE_CORRESPONDANCE_A_CETTE_EXPRESSION',
  CONTIENT = 'CONTIENT',
}

export enum EtatJuridique {
  VIGUEUR = 'VIGUEUR',
  ABROGE_DIFF = 'ABROGE_DIFF',
  VIGUEUR_DIFF = 'VIGUEUR_DIFF',
  VIGUEUR_ETEN = 'VIGUEUR_ETEN',
  VIGUEUR_NON_ETEN = 'VIGUEUR_NON_ETEN',
  ABROGE = 'ABROGE',
  PERIME = 'PERIME',
  ANNULE = 'ANNULE',
  MODIFIE = 'MODIFIE',
  DISJOINT = 'DISJOINT',
  SUBSTITUE = 'SUBSTITUE',
  TRANSFERE = 'TRANSFERE',
  INITIALE = 'INITIALE',
  MODIFIE_MORT_NE = 'MODIFIE_MORT_NE',
  SANS_ETAT = 'SANS_ETAT',
  DENONCE = 'DENONCE',
  REMPLACE = 'REMPLACE',
}

export enum Facette {
  NOM_CODE = 'NOM_CODE',
  DATE_SIGNATURE = 'DATE_SIGNATURE',
  DATE_VERSION = 'DATE_VERSION',
  DATE_PUBLICATION = 'DATE_PUBLICATION',
  TEXT_LEGAL_STATUS = 'TEXT_LEGAL_STATUS',
  ARTICLE_LEGAL_STATUS = 'ARTICLE_LEGAL_STATUS',
  NATURE = 'NATURE',
  NOR = 'NOR',
}

export enum TypePagination {
  DEFAUT = 'DEFAUT',
  ARTICLE = 'ARTICLE',
}

export enum Sort {
  PERTINENCE = 'PERTINENCE',
  PUBLICATION_DATE_ASC = 'PUBLICATION_DATE_ASC',
  PUBLICATION_DATE_DESC = 'PUBLICATION_DATE_DESC',
  SIGNATURE_DATE_ASC = 'SIGNATURE_DATE_ASC',
  SIGNATURE_DATE_DESC = 'SIGNATURE_DATE_DESC',
  ID_ASC = 'ID_ASC',
  ID_DESC = 'ID_DESC',
}

export enum SortJuri {
  PERTINENCE = 'PERTINENCE',
  DATE_DESC = 'DATE_DESC',
  DATE_ASC = 'DATE_ASC',
}

export enum PublicationStatus {
  PUBLIER = 'Publier',
  NON_PUBLIER = 'Non publier',
  PUBLIER_EXTRAIT = 'Publier extrait',
}

export enum FacettesJuri {
  CASSATION_TYPE_PUBLICATION_BULLETIN = 'CASSATION_TYPE_PUBLICATION_BULLETIN',
  JURIDICTION_JUDICIAIRE = 'JURIDICTION_JUDICIAIRE',
  CASSATION_FORMATION = 'CASSATION_FORMATION',
  APPEL_SIEGE_APPEL = 'APPEL_SIEGE_APPEL',
  DATE_DECISION = 'DATE_DECISION',
  DATE_PUBLI = 'DATE_PUBLI',
}

